version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chat_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
      - redis
      - bot
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - SERVITIN_CHATIK_ZMQ_CONNECT_ADDRESS=tcp://bot:5555

  bot:
    build: .
    command: python manage.py run_servitin
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    depends_on:
      - db
      - migration
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - SERVITIN_CHATIK_ZMQ_BIND_ADDRESS=tcp://*:5555

  redis:
    image: redis

  migration:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - DJANGO_SU_NAME=admin
      - DJANGO_SU_EMAIL=admin@admin.com
      - DJANGO_SU_PASSWORD=123456

  clear_users:
    build: .
    command: python manage.py clear_users
    volumes:
      - .:/code
    depends_on:
      - db
      - migration
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis

volumes:
  postgres: