# Generated by Django 3.2.6 on 2021-08-22 00:35

import chatik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, validators=[chatik.models.validate_room_name, chatik.models.validate_room_min_length]),
        ),
    ]
