# Generated by Django 3.2.6 on 2021-08-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatik', '0002_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
