# Generated by Django 3.2.6 on 2021-08-23 02:18

import chatik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatik', '0006_auto_20210822_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[chatik.models.validate_nickname_min_length, chatik.models.validate_nickname_unique]),
        ),
    ]
