# Generated by Django 3.2.6 on 2021-08-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatik', '0007_alter_chatuser_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.ManyToManyField(to='chatik.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatik.chatuser')),
            ],
        ),
    ]
