# Generated by Django 3.2.6 on 2021-08-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatik', '0008_roomuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomUser',
        ),
    ]
