# Generated by Django 3.2.6 on 2021-08-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatik', '0009_delete_roomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatik.room'),
        ),
    ]
