# Generated by Django 3.2.6 on 2021-08-24 21:51

import chatik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatik', '0010_chatuser_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[chatik.models.validate_nickname_min_length]),
        ),
    ]
